export const MAKING_POST = "MAKING_POST"
export const REACT_POST = "REACT_POST"

export const FETCH_POST = "FETCH_POST"
export const FETCH_POST_START = "FETCH_POST_START"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE"