export const MAKING_POST = "MAKING_POST"
export const REACT_POST = "REACT_POST"
export const PUSH_NEW_POST = "PUSH_NEW_POST"
export const COMMENT_POST = "COMMENT_POST"

export const FETCH_MORE_POST = "FETCH_MORE_POST"  // USE IN socket saga

export const FETCH_MORE_POST_START = "FETCH_MORE_POST_START"  // USE IN REDUCER
export const FETCH_MORE_POST_SUCCESS = "FETCH_MORE_POST_SUCCESS"  // USE IN REDUCER
export const FETCH_MORE_POST_FAILURE = "FETCH_MORE_POST_FAILURE" 
 
export const FETCH_POST = "FETCH_POST"
export const FETCH_POST_START = "FETCH_POST_START"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE"