export const LOGIN = "LOGIN"
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGIN_GOOGLE = "LOGIN_GOOGLE"
export const LOGIN_GOOGLE_START = "LOGIN_GOOGLE_START"
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS"
export const LOGIN_GOOGLE_FAILURE = "LOGIN_GOOGLE_FAILURE"

export const LOGOUT = "LOGOUT"
