export const LIST_GROUP = "LIST_GROUP"
export const SET_GROUP = "SET_GROUP"

export const LIST_GROUP_FAILED = "LIST_GROUP_FAILED"
export const LIST_GROUP_SUCCESS = "LIST_GROUP_SUCCESS"

export const SET_GROUP_FAILED = "SET_GROUP_FAILED"
export const SET_GROUP_SUCCESS = "SET_GROUP_SUCCESS"