export const LIST_GROUP = "LIST_GROUP"
export const SET_GROUP = "SET_GROUP"

export const LIST_GROUP_FAILED = "LIST_GROUP_FAILED"
export const LIST_GROUP_SUCCESS = "LIST_GROUP_SUCCESS"

export const FETCH_LOCATION = "FETCH_LOCATION"
export const SET_LOCATION_FAILED = "SET_LOCATION_FAILED"
export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS"